### ISSUE TITLE
Error after adding to plugins folder

### ISSUE THREAD

**Issue by ibrahimlawal** [PaystackHQ/plugin-OSClass#1]
[Escalated from payslack]

After adding to the plugins folder, user got an error when trying to install. The message was: 

```
Plugin couldn't be installed because of: Error importSQL::ModelPayment
payment/struct.sql
```

**Comment by Kendysond** [comment]
Hello Ibrahim, 

Thanks for sharing this. 

A user with the same issue fixed this by deleting the previous installation, and installing it again. 

I'll still look further to see if there is anything wrong with the import function.

**Comment by alllad** [comment]
I have the same problem

Error importSQL::ModelPayment payment/struct.sql

Pls help me to fix this.

Regards
